---

- name: Create a VIP, pool and pool members
  hosts: all
  connection: local

  vars:
    provider:
      password: admin
      server: 10.1.1.245
      user: admin
      validate_certs: no
      server_port: 443

  tasks:
    - name: Create a pool
      tags:
        - pool 
      bigip_pool:
        provider: "{{ provider }}"
        lb_method: ratio-member
        name: web
        slow_ramp_time: 120
      delegate_to: localhost


    - name: Add members to pool
      tags:
        - members
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: web
        port: "80"
      with_items:
        - host: 10.1.20.101
          name: web01
        - host: 10.1.20.102
          name: web02
        - host: 10.1.20.103
          name: web03
      delegate_to: localhost

    - name: Create a Virtual Server
      tags: 
        - virtual
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: web-vip
        destination: 172.16.10.108
        name: web_vip
        pool: web
        port: "80"
        snat: Automap
        profiles:
          - http
          - clientssl
      delegate_to: localhost